### ISSUE TITLE
Any reason not to use React Navigation 5?

### ISSUE THREAD

**Issue by resdevd** [nandorojo/expo-gatsby-navigation#2]
IMO, this library will be a greatly helpful with React Navigation 5. Right now React Navigation 5 doesn't support web yet, Is that the blocker? When it does support web, would this library be updated?
Great package by the way, makes integrating expo and gatsby easier. Thanks.

**Comment by nandorojo** [comment]
Hey @resdevd, thanks for writing, glad this could be of use for you.

This library doesn't currently support `react-navigation` v5, but I'm working on that now. In fact, the idea is that this package should work _even though_ `react-navigation` v5 doesn't work on web. Once this package is updated for v5, it technically shouldn't matter if react navigation supports web, since this will defer to gatsby for all routing/navigation.

I have to add some extra functionality to let this support v5 since the API changed a bit from v4. 

I have an open issue on a similar package: https://github.com/nandorojo/expo-next-react-navigation/issues/8

I'll try to get to it very soon and will keep you updated. Thanks again.

**Comment by resdevd** [comment]
> Hey @resdevd, thanks for writing, glad this could be of use for you.
> 
> This library doesn't currently support `react-navigation` v5, but I'm working on that now. In fact, the idea is that this package should work _even though_ `react-navigation` v5 doesn't work on web. Once this package is updated for v5, it technically shouldn't matter if react navigation supports web, since this will defer to gatsby for all routing/navigation.
> 
> I have to add some extra functionality to let this support v5 since the API changed a bit from v4.
> 
> I have an open issue on a similar package: [nandorojo/expo-next-react-navigation#8](https://github.com/nandorojo/expo-next-react-navigation/issues/8)
> 
> I'll try to get to it very soon and will keep you updated. Thanks again.

Thank you. Yes ofcourse, this library is great as it would enable everyone ( with Monorepos) adopt react navigation 5, in addition to painless management of gatsby routing with expo. I meant blocker in the context of usage as many monorepo projects with web sticking to react navigation 4. I’ll spread the word regarding this package to let everyone know there is alternative instead waiting for react navigation 5 web support. 

Keep up the great work.

**Comment by nandorojo** [comment]
Sounds good! Let me know if there's anything else I can help with.

**Comment by nandorojo** [comment]
`react-navigation` v5 should now work with #4:

```sh
yarn add expo-gatsby-navigation@v5
```

Going to close this issue for now. Feel free to try it out and let me know how it goes!

**Comment by resdevd** [comment]
Ironic enough, I've started exploring https://github.com/nandorojo/expo-next-react-navigation last week. In my usecase using expo-next feels like a better integration than expo-gatsby. So I've moved my projects to next-expo from gatsby-expo. 
While I can't test gatsby react-navigation 5 at the moment, I'll make sure to explore and test expo-next with react navigation 5 once https://github.com/nandorojo/expo-next-react-navigation/issues/8 is enhanced.

Regardless even with react-navigation 4, using https://github.com/nandorojo/expo-next-react-navigation making my code universal instead of .web.js files. Can't thank enough.

**Comment by nandorojo** [comment]
Glad to hear it’s useful! The real thanks goes to @evanbacon for expo web.

I’ll try to get v5 supported for the nextjs navigation library in the next few days, since I personally rely on that one more than gatsby too. I’m also going to make a package for navigation with expo and preact.

I’d love to see any universal projects you make using any of the packages — feel free to share if you ever want to.
